# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0005_auto_20160730_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo',
            name='album',
        ),
        migrations.AlterField(
            model_name='solo',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Track'),
        ),
    ]
